name: code quality
on:
  workflow_call:
jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
    
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: install dependencies
        run: pip install -r  requirement.txt
      - name: lint
        run: flake8 app.py
      - name: sast
        run: bandit -r app.py
