name: dependency.scan
on: workflow_call
jobs: 
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: check_code
        uses: actions/checkout@v4
        
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install pip audit
        run: pip install pip-audit
        
      - name: audit dependencies
        run: pip-audit -r requirement.txt
  
