name: deploy to server
on:
  workflow_call:
jobs:
  deploying:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKER_TAG: ${{ github.sha }} 
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: copy docker-compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.key}}
          source: docker-compose.yml
          target: ~/devops
      - name: ssh to pro server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.key}}
          script:  |
            echo " start deploy"
            mkdir -p devops
            sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
            sudo usermod -aG docker $USER
            export DOCKERUSER=${{ vars.DOCKERUSER }}
            DOCKER_TAG=${{ github.sha}}
            echo ${{ github.sha }}
            export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ vars.DOCKERUSER }} --password-stdin
            cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always
