name: deploy to server
on:
  workflow_call:
jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
       
      - name: ssh to pro server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.key}}
          script:  |
            echo " start deploy"
          
