name: devsecops end too end pipeline
on:
  push:
    branches: [main]
jobs:
  code-quality:
    name: code scan
    uses: ./.github/workflows/code-quality.yml
  secrects-scan:
    name: secrects scan
    uses: ./.github/workflows/secrects-scan.yml
  docker-scan:
    name: docker-scan
    uses: ./.github/workflows/docker-lint.yml
 
