name: devsecops end too end pipeline
on:
  push:
    branches: [main]
permissions:
  contents: write
  packages: write
jobs:
  code-quality:
    name: code scan
    uses: ./.github/workflows/code-quality.yml
  secrects-scan:
    name: secrects scan
    uses: ./.github/workflows/secrects-scan.yml
  docker-scan:
    name: docker-scan
    uses: ./.github/workflows/docker-lint.yml
  dependencies-scan:
    name: dependencies scan
    uses: ./.github/workflows/dependencies-scan.yml
  build:
    needs: [code-quality, secrects-scan, dependencies-scan, docker-scan]
    name: docker build
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
  trivy:
    needs: [build]
    uses: ./.github/workflows/image-scan.yml
