name: docker lint
on:
  workflow_call:
jobs:
  validate-dockerfile:
     runs-on: ubuntu-latest
     steps:
       - name: check_code
         uses: actions/checkout@v4
       - name: validate dockerfile
         uses: hadolint/hadolint-action@v3.1.0
         with:
           dockerfile: Dockerfile
